### ISSUE TITLE
First bunch floating window - navigation buttons not working

### ISSUE THREAD

**Issue by loseth** [ttscoff/bunch-docs#158]
The buttons at the bottom in the bunch-internal/first-bunch.html floating window does not respond to mouse clicks.
Probably because there is no other content to show for this particular window.
This was a source for some (short-lived) confusion, especially with the home button as I expected this to lead to some sort of overview screen.

**Comment by ttscoff** [comment]
I can see where that might be confusing on first run, but in the context of the Bunch it serves to demonstrate the `(display)` command with HTML files/websites, which I think is a good one to demo because it doesn't make any major changes to the environment or running apps, while also providing some pertinent info. I think the pros outweigh the cons.

Feedback noted, but closing this as I don't consider it in need of fixing. Thanks :).
